version: '1.0'

services:
  api:
    image: node:alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    networks:
      - backend
    command: sh -c "npm install && npm run start"

networks:
  backend:

volumes:
  node_modules: